//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QfbServer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceType", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    public enum SourceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeCoordinate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MeasuredValue = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HistoryData = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectPointSetting", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class ProjectPointSetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QfbServer.ServiceReference1.ProjectPointSetting[] ChildSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QfbServer.ServiceReference1.ProjectPointSetting[] ChildSettings {
            get {
                return this.ChildSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildSettingsField, value) != true)) {
                    this.ChildSettingsField = value;
                    this.RaisePropertyChanged("ChildSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO {
            get {
                return this.NOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOField, value) != true)) {
                    this.NOField = value;
                    this.RaisePropertyChanged("NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QualifiedRate", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QfbServer.ServiceReference1.QualifiedRateWarning))]
    public partial class QualifiedRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectSetting_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartsNO {
            get {
                return this.PartsNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsNOField, value) != true)) {
                    this.PartsNOField = value;
                    this.RaisePropertyChanged("PartsNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectSetting_Id {
            get {
                return this.ProjectSetting_IdField;
            }
            set {
                if ((this.ProjectSetting_IdField.Equals(value) != true)) {
                    this.ProjectSetting_IdField = value;
                    this.RaisePropertyChanged("ProjectSetting_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QCount {
            get {
                return this.QCountField;
            }
            set {
                if ((this.QCountField.Equals(value) != true)) {
                    this.QCountField = value;
                    this.RaisePropertyChanged("QCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QualifiedRateWarning", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class QualifiedRateWarning : QfbServer.ServiceReference1.QualifiedRate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWarningField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWarning {
            get {
                return this.IsWarningField;
            }
            set {
                if ((this.IsWarningField.Equals(value) != true)) {
                    this.IsWarningField = value;
                    this.RaisePropertyChanged("IsWarning");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CPKList", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class CPKList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AvgValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CPKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LowerToleranceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RangeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SigmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> StandardValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> UpperToleranceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AvgValue {
            get {
                return this.AvgValueField;
            }
            set {
                if ((this.AvgValueField.Equals(value) != true)) {
                    this.AvgValueField = value;
                    this.RaisePropertyChanged("AvgValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CPK {
            get {
                return this.CPKField;
            }
            set {
                if ((this.CPKField.Equals(value) != true)) {
                    this.CPKField = value;
                    this.RaisePropertyChanged("CPK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Ca {
            get {
                return this.CaField;
            }
            set {
                if ((this.CaField.Equals(value) != true)) {
                    this.CaField = value;
                    this.RaisePropertyChanged("Ca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cp {
            get {
                return this.CpField;
            }
            set {
                if ((this.CpField.Equals(value) != true)) {
                    this.CpField = value;
                    this.RaisePropertyChanged("Cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LowerTolerance {
            get {
                return this.LowerToleranceField;
            }
            set {
                if ((this.LowerToleranceField.Equals(value) != true)) {
                    this.LowerToleranceField = value;
                    this.RaisePropertyChanged("LowerTolerance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxValue {
            get {
                return this.MaxValueField;
            }
            set {
                if ((this.MaxValueField.Equals(value) != true)) {
                    this.MaxValueField = value;
                    this.RaisePropertyChanged("MaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinValue {
            get {
                return this.MinValueField;
            }
            set {
                if ((this.MinValueField.Equals(value) != true)) {
                    this.MinValueField = value;
                    this.RaisePropertyChanged("MinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointId {
            get {
                return this.PointIdField;
            }
            set {
                if ((this.PointIdField.Equals(value) != true)) {
                    this.PointIdField = value;
                    this.RaisePropertyChanged("PointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointNO {
            get {
                return this.PointNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PointNOField, value) != true)) {
                    this.PointNOField = value;
                    this.RaisePropertyChanged("PointNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointName {
            get {
                return this.PointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PointNameField, value) != true)) {
                    this.PointNameField = value;
                    this.RaisePropertyChanged("PointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RangeValue {
            get {
                return this.RangeValueField;
            }
            set {
                if ((this.RangeValueField.Equals(value) != true)) {
                    this.RangeValueField = value;
                    this.RaisePropertyChanged("RangeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sigma {
            get {
                return this.SigmaField;
            }
            set {
                if ((this.SigmaField.Equals(value) != true)) {
                    this.SigmaField = value;
                    this.RaisePropertyChanged("Sigma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> StandardValue {
            get {
                return this.StandardValueField;
            }
            set {
                if ((this.StandardValueField.Equals(value) != true)) {
                    this.StandardValueField = value;
                    this.RaisePropertyChanged("StandardValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> UpperTolerance {
            get {
                return this.UpperToleranceField;
            }
            set {
                if ((this.UpperToleranceField.Equals(value) != true)) {
                    this.UpperToleranceField = value;
                    this.RaisePropertyChanged("UpperTolerance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryData", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QfbServer.ServiceReference1.ValueWarnning))]
    public partial class HistoryData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointSetting_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartsNO {
            get {
                return this.PartsNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsNOField, value) != true)) {
                    this.PartsNOField = value;
                    this.RaisePropertyChanged("PartsNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Point {
            get {
                return this.PointField;
            }
            set {
                if ((object.ReferenceEquals(this.PointField, value) != true)) {
                    this.PointField = value;
                    this.RaisePropertyChanged("Point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointSetting_Id {
            get {
                return this.PointSetting_IdField;
            }
            set {
                if ((this.PointSetting_IdField.Equals(value) != true)) {
                    this.PointSetting_IdField = value;
                    this.RaisePropertyChanged("PointSetting_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueWarnning", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class ValueWarnning : QfbServer.ServiceReference1.HistoryData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWarningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LowerToleranceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UpperToleranceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWarning {
            get {
                return this.IsWarningField;
            }
            set {
                if ((this.IsWarningField.Equals(value) != true)) {
                    this.IsWarningField = value;
                    this.RaisePropertyChanged("IsWarning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LowerTolerance {
            get {
                return this.LowerToleranceField;
            }
            set {
                if ((this.LowerToleranceField.Equals(value) != true)) {
                    this.LowerToleranceField = value;
                    this.RaisePropertyChanged("LowerTolerance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UpperTolerance {
            get {
                return this.UpperToleranceField;
            }
            set {
                if ((this.UpperToleranceField.Equals(value) != true)) {
                    this.UpperToleranceField = value;
                    this.RaisePropertyChanged("UpperTolerance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeValue", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class DateTimeValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelayWarnning", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class DelayWarnning : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrendWarning", Namespace="http://schemas.datacontract.org/2004/07/TQCService")]
    [System.SerializableAttribute()]
    public partial class TrendWarning : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartsNO {
            get {
                return this.PartsNOField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsNOField, value) != true)) {
                    this.PartsNOField = value;
                    this.RaisePropertyChanged("PartsNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartsName {
            get {
                return this.PartsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsNameField, value) != true)) {
                    this.PartsNameField = value;
                    this.RaisePropertyChanged("PartsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointName {
            get {
                return this.PointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PointNameField, value) != true)) {
                    this.PointNameField = value;
                    this.RaisePropertyChanged("PointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetSettings", ReplyAction="http://tempuri.org/IWCFService/GetSettingsResponse")]
        QfbServer.ServiceReference1.ProjectPointSetting[] GetSettings(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetSettings", ReplyAction="http://tempuri.org/IWCFService/GetSettingsResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.ProjectPointSetting[]> GetSettingsAsync(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetPointIdsByProjectAndPointNO", ReplyAction="http://tempuri.org/IWCFService/GetPointIdsByProjectAndPointNOResponse")]
        int[] GetPointIdsByProjectAndPointNO(QfbServer.ServiceReference1.SourceType sourceType, System.Collections.Generic.KeyValuePair<int, string>[] kvp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetPointIdsByProjectAndPointNO", ReplyAction="http://tempuri.org/IWCFService/GetPointIdsByProjectAndPointNOResponse")]
        System.Threading.Tasks.Task<int[]> GetPointIdsByProjectAndPointNOAsync(QfbServer.ServiceReference1.SourceType sourceType, System.Collections.Generic.KeyValuePair<int, string>[] kvp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByDate", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByDateResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByDate(System.DateTime startTime, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByDate", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByDateResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByDateAsync(System.DateTime startTime, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTime", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTime(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTime", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAsync(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeWithPage", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeWithPageResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeWithPage(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeWithPage", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeWithPageResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeWithPageAsync(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOs", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndNOs(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOs", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndNOsAsync(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsWithPage", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsWithPageResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndNOsWithPage(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, int skip, int take, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsWithPage", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndNOsWithPageResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndNOsWithPageAsync(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, int skip, int take, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndProjrct", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndProjrctResponse")]
        QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndProjrct(System.DateTime startTime, System.DateTime endTime, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndProjrct", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateByTimeAndProjrctResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndProjrctAsync(System.DateTime startTime, System.DateTime endTime, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetCPKDataByTimeAndPoints", ReplyAction="http://tempuri.org/IWCFService/GetCPKDataByTimeAndPointsResponse")]
        QfbServer.ServiceReference1.CPKList[] GetCPKDataByTimeAndPoints(System.DateTime startTime, System.DateTime endTime, int[] pointIds, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetCPKDataByTimeAndPoints", ReplyAction="http://tempuri.org/IWCFService/GetCPKDataByTimeAndPointsResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.CPKList[]> GetCPKDataByTimeAndPointsAsync(System.DateTime startTime, System.DateTime endTime, int[] pointIds, QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByDate", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByDateResponse")]
        QfbServer.ServiceReference1.HistoryData[] GetHistoryDataByDate(long pointId, System.DateTime startTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByDate", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByDateResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.HistoryData[]> GetHistoryDataByDateAsync(long pointId, System.DateTime startTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByTime", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByTimeResponse")]
        QfbServer.ServiceReference1.HistoryData[] GetHistoryDataByTime(long pointId, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByTime", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.HistoryData[]> GetHistoryDataByTimeAsync(long pointId, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByTimeAndPoints", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByTimeAndPointsResponse")]
        System.Collections.Generic.Dictionary<string, QfbServer.ServiceReference1.DateTimeValue[]> GetHistoryDataByTimeAndPoints(System.DateTime startTime, System.DateTime endTime, int[] pointIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetHistoryDataByTimeAndPoints", ReplyAction="http://tempuri.org/IWCFService/GetHistoryDataByTimeAndPointsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, QfbServer.ServiceReference1.DateTimeValue[]>> GetHistoryDataByTimeAndPointsAsync(System.DateTime startTime, System.DateTime endTime, int[] pointIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/StartStatic", ReplyAction="http://tempuri.org/IWCFService/StartStaticResponse")]
        void StartStatic(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/StartStatic", ReplyAction="http://tempuri.org/IWCFService/StartStaticResponse")]
        System.Threading.Tasks.Task StartStaticAsync(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetChartValue", ReplyAction="http://tempuri.org/IWCFService/GetChartValueResponse")]
        QfbServer.ServiceReference1.DateTimeValue[] GetChartValue(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetChartValue", ReplyAction="http://tempuri.org/IWCFService/GetChartValueResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.DateTimeValue[]> GetChartValueAsync(QfbServer.ServiceReference1.SourceType sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDelayWarning", ReplyAction="http://tempuri.org/IWCFService/GetDelayWarningResponse")]
        QfbServer.ServiceReference1.DelayWarnning[] GetDelayWarning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDelayWarning", ReplyAction="http://tempuri.org/IWCFService/GetDelayWarningResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.DelayWarnning[]> GetDelayWarningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDelayWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetDelayWarningByTimeResponse")]
        QfbServer.ServiceReference1.DelayWarnning[] GetDelayWarningByTime(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDelayWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetDelayWarningByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.DelayWarnning[]> GetDelayWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeResponse")]
        QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTime(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarning", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningResponse")]
        QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTimeWithWarning(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarning", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeWithWarningAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningAndNO", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningAndNOResponse")]
        QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTimeWithWarningAndNO(System.DateTime startTime, System.DateTime endTime, string projectNO, string partsNO, string itemNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningAndNO", ReplyAction="http://tempuri.org/IWCFService/GetValueWarningByTimeWithWarningAndNOResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeWithWarningAndNOAsync(System.DateTime startTime, System.DateTime endTime, string projectNO, string partsNO, string itemNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetTrendWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetTrendWarningByTimeResponse")]
        QfbServer.ServiceReference1.TrendWarning[] GetTrendWarningByTime(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetTrendWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetTrendWarningByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.TrendWarning[]> GetTrendWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeResponse")]
        QfbServer.ServiceReference1.QualifiedRateWarning[] GetQualifiedRateWarningByTime(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTime", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRateWarning[]> GetQualifiedRateWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeAndRate", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeAndRateResponse")]
        QfbServer.ServiceReference1.QualifiedRateWarning[] GetQualifiedRateWarningByTimeAndRate(System.DateTime startTime, System.DateTime endTime, double rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeAndRate", ReplyAction="http://tempuri.org/IWCFService/GetQualifiedRateWarningByTimeAndRateResponse")]
        System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRateWarning[]> GetQualifiedRateWarningByTimeAndRateAsync(System.DateTime startTime, System.DateTime endTime, double rate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : QfbServer.ServiceReference1.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<QfbServer.ServiceReference1.IWCFService>, QfbServer.ServiceReference1.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QfbServer.ServiceReference1.ProjectPointSetting[] GetSettings(QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetSettings(sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.ProjectPointSetting[]> GetSettingsAsync(QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetSettingsAsync(sourceType);
        }
        
        public int[] GetPointIdsByProjectAndPointNO(QfbServer.ServiceReference1.SourceType sourceType, System.Collections.Generic.KeyValuePair<int, string>[] kvp) {
            return base.Channel.GetPointIdsByProjectAndPointNO(sourceType, kvp);
        }
        
        public System.Threading.Tasks.Task<int[]> GetPointIdsByProjectAndPointNOAsync(QfbServer.ServiceReference1.SourceType sourceType, System.Collections.Generic.KeyValuePair<int, string>[] kvp) {
            return base.Channel.GetPointIdsByProjectAndPointNOAsync(sourceType, kvp);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByDate(System.DateTime startTime, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByDate(startTime, sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByDateAsync(System.DateTime startTime, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByDateAsync(startTime, sourceType);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTime(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTime(startTime, endTime, sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAsync(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTimeAsync(startTime, endTime, sourceType);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeWithPage(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType, int skip, int take) {
            return base.Channel.GetQualifiedRateByTimeWithPage(startTime, endTime, sourceType, skip, take);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeWithPageAsync(System.DateTime startTime, System.DateTime endTime, QfbServer.ServiceReference1.SourceType sourceType, int skip, int take) {
            return base.Channel.GetQualifiedRateByTimeWithPageAsync(startTime, endTime, sourceType, skip, take);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndNOs(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTimeAndNOs(startTime, endTime, projcetNO, partsNO, itemNO, sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndNOsAsync(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTimeAndNOsAsync(startTime, endTime, projcetNO, partsNO, itemNO, sourceType);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndNOsWithPage(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, int skip, int take, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTimeAndNOsWithPage(startTime, endTime, projcetNO, partsNO, itemNO, skip, take, sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndNOsWithPageAsync(System.DateTime startTime, System.DateTime endTime, string projcetNO, string partsNO, string itemNO, int skip, int take, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetQualifiedRateByTimeAndNOsWithPageAsync(startTime, endTime, projcetNO, partsNO, itemNO, skip, take, sourceType);
        }
        
        public QfbServer.ServiceReference1.QualifiedRate[] GetQualifiedRateByTimeAndProjrct(System.DateTime startTime, System.DateTime endTime, int id) {
            return base.Channel.GetQualifiedRateByTimeAndProjrct(startTime, endTime, id);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRate[]> GetQualifiedRateByTimeAndProjrctAsync(System.DateTime startTime, System.DateTime endTime, int id) {
            return base.Channel.GetQualifiedRateByTimeAndProjrctAsync(startTime, endTime, id);
        }
        
        public QfbServer.ServiceReference1.CPKList[] GetCPKDataByTimeAndPoints(System.DateTime startTime, System.DateTime endTime, int[] pointIds, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetCPKDataByTimeAndPoints(startTime, endTime, pointIds, sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.CPKList[]> GetCPKDataByTimeAndPointsAsync(System.DateTime startTime, System.DateTime endTime, int[] pointIds, QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetCPKDataByTimeAndPointsAsync(startTime, endTime, pointIds, sourceType);
        }
        
        public QfbServer.ServiceReference1.HistoryData[] GetHistoryDataByDate(long pointId, System.DateTime startTime) {
            return base.Channel.GetHistoryDataByDate(pointId, startTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.HistoryData[]> GetHistoryDataByDateAsync(long pointId, System.DateTime startTime) {
            return base.Channel.GetHistoryDataByDateAsync(pointId, startTime);
        }
        
        public QfbServer.ServiceReference1.HistoryData[] GetHistoryDataByTime(long pointId, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetHistoryDataByTime(pointId, startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.HistoryData[]> GetHistoryDataByTimeAsync(long pointId, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetHistoryDataByTimeAsync(pointId, startTime, endTime);
        }
        
        public System.Collections.Generic.Dictionary<string, QfbServer.ServiceReference1.DateTimeValue[]> GetHistoryDataByTimeAndPoints(System.DateTime startTime, System.DateTime endTime, int[] pointIds) {
            return base.Channel.GetHistoryDataByTimeAndPoints(startTime, endTime, pointIds);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, QfbServer.ServiceReference1.DateTimeValue[]>> GetHistoryDataByTimeAndPointsAsync(System.DateTime startTime, System.DateTime endTime, int[] pointIds) {
            return base.Channel.GetHistoryDataByTimeAndPointsAsync(startTime, endTime, pointIds);
        }
        
        public void StartStatic(QfbServer.ServiceReference1.SourceType sourceType) {
            base.Channel.StartStatic(sourceType);
        }
        
        public System.Threading.Tasks.Task StartStaticAsync(QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.StartStaticAsync(sourceType);
        }
        
        public QfbServer.ServiceReference1.DateTimeValue[] GetChartValue(QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetChartValue(sourceType);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.DateTimeValue[]> GetChartValueAsync(QfbServer.ServiceReference1.SourceType sourceType) {
            return base.Channel.GetChartValueAsync(sourceType);
        }
        
        public QfbServer.ServiceReference1.DelayWarnning[] GetDelayWarning() {
            return base.Channel.GetDelayWarning();
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.DelayWarnning[]> GetDelayWarningAsync() {
            return base.Channel.GetDelayWarningAsync();
        }
        
        public QfbServer.ServiceReference1.DelayWarnning[] GetDelayWarningByTime(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetDelayWarningByTime(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.DelayWarnning[]> GetDelayWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetDelayWarningByTimeAsync(startTime, endTime);
        }
        
        public QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTime(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetValueWarningByTime(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetValueWarningByTimeAsync(startTime, endTime);
        }
        
        public QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTimeWithWarning(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetValueWarningByTimeWithWarning(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeWithWarningAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetValueWarningByTimeWithWarningAsync(startTime, endTime);
        }
        
        public QfbServer.ServiceReference1.ValueWarnning[] GetValueWarningByTimeWithWarningAndNO(System.DateTime startTime, System.DateTime endTime, string projectNO, string partsNO, string itemNO) {
            return base.Channel.GetValueWarningByTimeWithWarningAndNO(startTime, endTime, projectNO, partsNO, itemNO);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.ValueWarnning[]> GetValueWarningByTimeWithWarningAndNOAsync(System.DateTime startTime, System.DateTime endTime, string projectNO, string partsNO, string itemNO) {
            return base.Channel.GetValueWarningByTimeWithWarningAndNOAsync(startTime, endTime, projectNO, partsNO, itemNO);
        }
        
        public QfbServer.ServiceReference1.TrendWarning[] GetTrendWarningByTime(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetTrendWarningByTime(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.TrendWarning[]> GetTrendWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetTrendWarningByTimeAsync(startTime, endTime);
        }
        
        public QfbServer.ServiceReference1.QualifiedRateWarning[] GetQualifiedRateWarningByTime(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetQualifiedRateWarningByTime(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRateWarning[]> GetQualifiedRateWarningByTimeAsync(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetQualifiedRateWarningByTimeAsync(startTime, endTime);
        }
        
        public QfbServer.ServiceReference1.QualifiedRateWarning[] GetQualifiedRateWarningByTimeAndRate(System.DateTime startTime, System.DateTime endTime, double rate) {
            return base.Channel.GetQualifiedRateWarningByTimeAndRate(startTime, endTime, rate);
        }
        
        public System.Threading.Tasks.Task<QfbServer.ServiceReference1.QualifiedRateWarning[]> GetQualifiedRateWarningByTimeAndRateAsync(System.DateTime startTime, System.DateTime endTime, double rate) {
            return base.Channel.GetQualifiedRateWarningByTimeAndRateAsync(startTime, endTime, rate);
        }
    }
}
